version: '1.0'
services:
  rabbitmq-notify:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword_utm
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      - ms-network

  worker-telegram:
    image: 'worker:v0.1'
    environment:
      spring.rabbitmq.host: rabbitmq-notify
      spring.rabbitmq.port: 5672
      spring.rabbitmq.username: rmuser
      spring.rabbitmq.password: rmpassword_utm
      server.port: 8085
      spring.application.name: worker-telegram
      spring.profiles.active: telegram,dev
      application.tokens.telegram: ${TOKEN_TELEGRAM}
      application.tokens.viber: ${TOKEN_VIBER}
    depends_on:
      - rabbitmq-notify
    ports:
      - '8085:8085'
    networks:
      - ms-network
  worker-viber:
    image: 'worker:v0.1'
    environment:
      spring.rabbitmq.host: rabbitmq-notify
      spring.rabbitmq.port: 5672
      spring.rabbitmq.username: rmuser
      spring.rabbitmq.password: rmpassword_utm
      server.port: 8086
      spring.application.name: worker-viber
      spring.profiles.active: viber,dev
      application.tokens.telegram: ${TOKEN_TELEGRAM}
      application.tokens.viber: ${TOKEN_VIBER}
    depends_on:
      - rabbitmq-notify
    ports:
      - '8086:8086'
    networks:
      - ms-network

networks:
  ms-network:
    driver: bridge
